### PR TITLE
Add teleportation items for Clue compass

### PR DESCRIPTION
**Pull request by joranvar**
It took me a while to be able to test, but here are some entries for the Clue compass.
I am not sure how/if there is a test to see which regions are unlocked, but I added the ones for Asgarnia, Karamja, Misthalin and Kourend.

### CODE REVIEW

**Comment by Skretzo** [comment]
Thank you.

It should be possible to see which regions are unlocked by looking at Varbits and/or VarPlayers. It is probably one varbit for each region that can be 0 (not unlocked) or 1 (unlocked), but they could also be packing multiple region unlocks into a single varbit. 

Many varbits are already documented [on the wiki](https://oldschool.runescape.wiki/w/RuneScape:Varbit) or [on the wiki tool server](https://chisel.weirdgloop.org/varbs/index), but new varbits are often missing.

Sometimes people in the RuneLite discord or Quest Helper discord have figured out these varbits, but if not then someone needs to enable developer mode in the client via `--developer-mode`, open up the "Var inspector" from the developer mode side panel, and perform one or more region unlocks to see which Varbit/VarPlayer holds this information.

Sometimes you can get away with not actually performing server side varbit changes if the same varbit is reused in some kind of UI. Then you can test it by triggering client-side varbit changes via in-game chat messages like `::getvarb <varbit-id>` and `::setvarb <varbit-id> <value>` for Varbits, and `::getvarp <varplayer-id>` and `::setvarp <varplayer-id> <value>` for VarPlayers. These chat messages also require having enabled developer mode. I probably won't be able to gather these varbits/varplayers myself for a few weeks, so feel free to help out.

**Comment by adamk33n3r** [comment]
https://oldschool.runescape.wiki/w/RuneScape:Varbit/10664
https://oldschool.runescape.wiki/w/RuneScape:Varbit/10665
https://oldschool.runescape.wiki/w/RuneScape:Varbit/10666

These will get you the regions unlocked! Technically there's also https://oldschool.runescape.wiki/w/RuneScape:Varbit/10663 but that should always be karamja once players finish the tutorial.

**Comment by joranvar** [comment]
Ah, thanks for those pointers! I will look into those.

**Comment by adamk33n3r** [comment]
So excited for this to work! Is there anything you need to get the rest of the regions in?

**Comment by joranvar** [comment]
For now, all destinations are added without any region unlock checks. That may give impossible paths when the closest teleport happen to be in a locked region, but usually a target within the unlocked region has a closer clue compass destination anyway? I have not checked that.

Will look into region unlocks later today.

**Comment by adamk33n3r** [comment]
> For now, all destinations are added without any region unlock checks.

Isn't that checking the varbits here? https://github.com/Skretzo/shortest-path/pull/123/files#diff-5dc68336c6688f0704cee058bf70da630507c70ea7e8bab6a46877a93d4a1144R333

**Comment by joranvar** [comment]
Yes, I just had enough time (but now I have to run, haha) to add a check for each region. But I don't like this solution very much, so I'll look into a better check later.

**Comment by Skretzo** [comment]
> For now, all destinations are added without any region unlock checks. That may give impossible paths when the closest teleport happen to be in a locked region, but usually a target within the unlocked region has a closer clue compass destination anyway? I have not checked that.

I think adding all destinations without any region unlocks might be the best thing to do for now, since leagues won't be around too long and review before releasing to live RuneLite typically takes a week. It is correct that the varbit check is only passing if all included varbits are correct. I have not yet gotten around to implement parsing of combinations of OR and AND, and I feel like we probably shouldn't rush to add that now.

**Comment by joranvar** [comment]
I agree, no need to make this PR larger with an implementation that can handle OR/AND varbits.
I think this might be ready as is, in that case, I added/generated the permutations already. They could do with an extra check, maybe, but they seemed to work for me.

**Comment by Skretzo** [comment]
I will make a release for this now. If many people report incorrect paths then we can consider doing something more.

**Pull request merged**
